[keys]
# CircleCI 
circleci_org_slug = "YOUR_CIRCLECI_ORG_SLUG" # Akin to github/your_user_name
circleci_org_id = "YOUR_CIRCLECI_ORG_ID" # The ID of your org - get it in org settings
circleci_token = "YOUR_CIRCLECI_TOKEN" # Generate in CircleCI account settings

# Third party
snyk_token = "YOUR_SNYK_TOKEN"
docker_login = "YOUR_DOCKER_USERNAME"
docker_token = "YOUR_DOCKER_TOKEN"
tf_cloud_key = YOUR_TERRAFORM_CLOUD_KEY
digitalocean_token = "YOUR_DIGITALOCEAN_TOKEN"
