version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          command: |
            npm install
      - run:
          command: |
            npm run lint
            npm run test 
            npm run build 
            
workflows:
  build_test_deploy:
      jobs:
        - build      

# VS Code Extension Version: 1.0.2